# Generated by Django 4.0.1 on 2022-01-27 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='UID',
            new_name='uid',
        ),
    ]
