# Generated by Django 4.0.1 on 2022-01-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_rename_uid_customer_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vehicleModel',
            field=models.CharField(max_length=50),
        ),
    ]
